"""Writes src/Media.xaml: the Icon<Role> geometries, drawn on a 16x16 grid out of whole-pixel rectangles.

Original artwork for this theme. The shapes are blocky on purpose, like the 1px VGUI glyphs and the Marlett symbol
font the game's windows use (nothing is taken or traced from the game). Every rectangle is wound clockwise, so the
union fills with the default nonzero rule and stays crisp at whole-pixel sizes (16, 32).
Run from anywhere: python3 art/icons.py
"""
from pathlib import Path

MEDIA = Path(__file__).resolve().parent.parent / "src" / "Media.xaml"


def outline(x, y, w, h, t=1):
    return [(x, y, w, t), (x, y + h - t, w, t), (x, y, t, h), (x + w - t, y, t, h)]


ICONS = {
    # text / search
    "Search": [(4, 2, 4, 2), (4, 8, 4, 2), (2, 4, 2, 4), (8, 4, 2, 4), (3, 3, 1, 1), (8, 3, 1, 1), (3, 8, 1, 1), (8, 8, 1, 1)] + [(9 + i, 9 + i, 2, 2) for i in range(5)],
    "Clear": [(3 + i, 3 + i, 2, 1) for i in range(10)] + [(11 - i, 3 + i, 2, 1) for i in range(10)],
    # top panel
    "ViewSettings": [(2, 3, 12, 1), (9, 2, 3, 3), (2, 8, 12, 1), (4, 7, 3, 3), (2, 13, 12, 1), (8, 12, 3, 3)],
    "FilterPresets": [(4, 2, 8, 1), (4, 3, 1, 10), (11, 3, 1, 10), (5, 13, 1, 1), (6, 12, 1, 1), (7, 11, 2, 1), (9, 12, 1, 1), (10, 13, 1, 1)],
    "Group": outline(2, 2, 8, 8) + outline(6, 6, 8, 8),
    "Sort": [(2, 3, 12, 2), (2, 7, 8, 2), (2, 11, 4, 2)],
    "DetailsView": [(2, 3, 2, 2), (5, 3, 9, 2), (2, 7, 2, 2), (5, 7, 9, 2), (2, 11, 2, 2), (5, 11, 9, 2)],
    "GridView": [(2, 2, 5, 5), (9, 2, 5, 5), (2, 9, 5, 5), (9, 9, 5, 5)],
    "ListView": [(2, 3, 12, 3), (2, 7, 12, 3), (2, 11, 12, 3)],
    "Update": [(7, 2, 2, 6), (4, 8, 8, 1), (5, 9, 6, 1), (6, 10, 4, 1), (7, 11, 2, 1), (2, 13, 12, 1), (2, 11, 1, 2), (13, 11, 1, 2)],
    "Explorer": [(2, 3, 5, 2)] + outline(2, 5, 12, 9),
    "Random": outline(2, 2, 12, 12) + [(5, 5, 2, 2), (9, 5, 2, 2), (7, 7, 2, 2), (5, 9, 2, 2), (9, 9, 2, 2)],
    "ViewRandom": outline(2, 2, 12, 12) + [(4, 4, 2, 2), (7, 7, 2, 2), (10, 10, 2, 2)],
    "Filter": [(2, 3, 12, 2), (4, 5, 8, 2), (6, 7, 4, 2), (6, 9, 4, 4)],
    "Notifications": [(7, 1, 2, 2), (6, 3, 4, 1), (5, 4, 6, 1), (4, 5, 8, 6), (3, 11, 10, 2), (7, 13, 2, 2)],
    "MainMenu": [(2, 3, 12, 2), (2, 7, 12, 2), (2, 11, 12, 2)],
    # sidebar
    "Library": [(2, 3, 3, 10), (6, 2, 3, 11), (10, 4, 4, 9)],
    "Statistics": [(2, 9, 3, 5), (6, 5, 3, 9), (10, 2, 3, 12)],
    # window buttons
    "WindowMinimize": [(3, 11, 9, 2)],
    "WindowMaximize": outline(3, 3, 10, 10) + [(3, 3, 10, 2)],
    "WindowRestore": outline(2, 6, 8, 8) + [(2, 6, 8, 2), (5, 2, 9, 2), (12, 4, 2, 6)],
    "WindowClose": [(3 + i, 3 + i, 2, 1) for i in range(10)] + [(11 - i, 3 + i, 2, 1) for i in range(10)],
    # indicators
    "DropDown": [(3, 5, 10, 1), (4, 6, 8, 1), (5, 7, 6, 1), (6, 8, 4, 1), (7, 9, 2, 1)],
    "Submenu": [(5, 3, 1, 10), (6, 4, 1, 8), (7, 5, 1, 6), (8, 6, 1, 4), (9, 7, 1, 2)],
    "Check": [(3, 7, 2, 2), (4, 8, 2, 2), (5, 9, 2, 2), (6, 10, 2, 2), (7, 9, 2, 2), (8, 8, 2, 2), (9, 7, 2, 2), (10, 6, 2, 2), (11, 5, 2, 2), (12, 4, 2, 2)],
    # actions
    "Add": [(7, 3, 2, 10), (3, 7, 10, 2)],
    "Edit": [(3 + i, 10 - i, 3, 2) for i in range(8)] + [(2, 12, 2, 2)],
    "Remove": [(3, 3, 10, 2), (6, 2, 4, 1), (4, 5, 1, 9), (11, 5, 1, 9), (4, 13, 8, 1), (6, 7, 1, 5), (9, 7, 1, 5)],
    "Options": outline(4, 4, 8, 8) + [(7, 1, 2, 3), (7, 12, 2, 3), (1, 7, 3, 2), (12, 7, 3, 2), (7, 7, 2, 2)],
    "Play": [(4, 2, 1, 12), (5, 3, 1, 10), (6, 4, 1, 8), (7, 5, 1, 6), (8, 6, 1, 4), (9, 7, 1, 2)],
    "Info": outline(2, 2, 12, 12) + [(7, 4, 2, 2), (7, 7, 2, 5)],
    "Download": [(7, 2, 2, 6), (4, 8, 8, 1), (5, 9, 6, 1), (6, 10, 4, 1), (7, 11, 2, 1), (2, 13, 12, 1), (2, 11, 1, 2), (13, 11, 1, 2)],
}


HEADER = """<!--
    Overlay on Playnite Default/Media.xaml. GENERATED by art/icons.py: edit the script, not this file.
    Icon set: original, blocky 16x16 pixel glyphs in the spirit of VGUI's Marlett symbols (no third-party icon set,
    so there is no icon license to ship). Each Icon<Role> is one path on a 16-unit grid, filled by IconTemplate in the
    inherited foreground; the host sets the size (IconSize).

    Menu icons (AddGameIcon, PlayIcon, ...) stay Playnite's own icofont glyphs, which already read TextBrush, so they
    come out amber here.
-->
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:sys="clr-namespace:System;assembly=mscorlib">

"""

FOOTER = """
    <!-- Content = one of the geometries above, filled in the inherited foreground. -->
    <DataTemplate x:Key="IconTemplate">
        <Viewbox Stretch="Uniform">
            <Canvas Width="16" Height="16" SnapsToDevicePixels="True">
                <Path Data="{Binding}"
                      Fill="{Binding (TextElement.Foreground), RelativeSource={RelativeSource Self}}" />
            </Canvas>
        </Viewbox>
    </DataTemplate>

    <DataTemplate x:Key="SearchTextIconTemplate">
        <ContentPresenter Width="14" Height="14"
                          Content="{DynamicResource IconSearch}"
                          ContentTemplate="{DynamicResource IconTemplate}" />
    </DataTemplate>

    <DataTemplate x:Key="ClearTextIconTemplate">
        <ContentPresenter Width="12" Height="12"
                          Content="{DynamicResource IconClear}"
                          ContentTemplate="{DynamicResource IconTemplate}" />
    </DataTemplate>
</ResourceDictionary>
"""


def geometry(rects):
    parts = []
    for x, y, w, h in rects:
        parts.append(f"M {x} {y} h {w} v {h} h -{w} Z")
    return "F1 " + " ".join(parts)


def main():
    out = [HEADER]
    for name, rects in ICONS.items():
        out.append(f'    <Geometry x:Key="Icon{name}">{geometry(rects)}</Geometry>\n')
    out.append(FOOTER)
    MEDIA.write_text("".join(out), encoding="utf-8")
    print(f"wrote {MEDIA} ({len(ICONS)} icons)")


if __name__ == "__main__":
    main()
