#!/usr/bin/env python3
"""Writes art/preview-details.html and art/preview-settings.html: approximate HTML replicas of Blacklist in Playnite
(same tokens, sizes, shell and chrome as the XAML), rendered to details.png / settings.png by
scripts/take-screenshots.ps1. Icons are inlined from the Phosphor bold SVGs that art/icons.py caches in art/.cache
(run icons.py first). Not shipped in the package.

    python3 art/previews.py          (from src/themes/Blacklist)
"""
import pathlib, re

ART = pathlib.Path(__file__).resolve().parent
CACHE = ART / ".cache"
TOKENS = (ART.parent / "src" / "tokens.css").read_text(encoding="utf-8")
T = dict(re.findall(r"--(mw-[a-z0-9-]+):\s*(#[0-9a-fA-F]{6})", TOKENS))


FONTS_CSS = "https://fonts.googleapis.com/css2?family=Saira+Semi+Condensed:wght@400;700&family=UnifrakturMaguntia&display=block"


def fonts():
    """Stand-ins for Eurostile and the blackletter title face (both OFL, Google Fonts), inlined as data URIs so the
    headless renderer needs no network. Latin subset only; cached in art/.cache."""
    import base64, urllib.request
    CACHE.mkdir(exist_ok=True)
    css_file = CACHE / "fonts.css"
    if not css_file.exists():
        req = urllib.request.Request(FONTS_CSS, headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"})
        css_file.write_bytes(urllib.request.urlopen(req, timeout=30).read())
    css = css_file.read_text(encoding="utf-8")
    out = []
    for block in re.findall(r"/\* latin \*/\s*(@font-face \{.*?\})", css, re.S):
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        f = CACHE / url.rsplit("/", 1)[1]
        if not f.exists():
            f.write_bytes(urllib.request.urlopen(url, timeout=30).read())
        data = "data:font/woff2;base64," + base64.b64encode(f.read_bytes()).decode()
        out.append(block.replace(url, data).replace("\n", " "))
    return "\n".join(out)


def icon(name, size=16, cls=""):
    svg = (CACHE / (name + ".svg")).read_text(encoding="utf-8")
    inner = svg[svg.index(">") + 1:svg.rindex("</svg>")]
    return ('<svg class="ic %s" width="%d" height="%d" viewBox="0 0 256 256" fill="currentColor">%s</svg>'
            % (cls, size, size, inner))


# Shared head: fonts (Google Fonts stand-ins for Eurostile and the blackletter title face), tokens, shell chrome.
HEAD = """<!doctype html>
<!-- Blacklist: approximate HTML replica of Playnite (%(what)s). GENERATED by art/previews.py: edit the script. -->
<html><head><meta charset="utf-8"><title>Blacklist - %(what)s</title>
<style>
%(fonts)s
:root{--black:%(mw-black)s;--page:%(mw-page)s;--shell:%(mw-shell)s;--bar:%(mw-bar)s;--panel:%(mw-panel)s;--raised:%(mw-panel-raised)s;
--dialog:%(mw-dialog)s;--cell:%(mw-cell)s;--select:%(mw-select)s;--edge:%(mw-edge)s;--rule:%(mw-rule)s;--amber:%(mw-amber)s;
--amber-strong:%(mw-amber-strong)s;--amber-dim:%(mw-amber-dim)s;--thumb:%(mw-amber-thumb)s;--stripe:%(mw-stripe-bright)s;
--text:%(mw-text)s;--bright:%(mw-text-bright)s;--dim:%(mw-text-dim)s;--ink:%(mw-ink)s;--red:%(mw-red)s;--lime:%(mw-lime)s;--heat:%(mw-heat)s;
--body:"Eurostile","Bahnschrift","Saira Semi Condensed",sans-serif;--title:"Old English Text MT","UnifrakturMaguntia",serif}
*{box-sizing:border-box;margin:0;padding:0}
body{width:1600px;height:900px;overflow:hidden;background:var(--page);color:var(--text);font-family:var(--body);font-size:14px;position:relative}
.ic{display:block}
.stripes{background:repeating-linear-gradient(-45deg,var(--stripe) 0 7px,var(--shell) 7px 14px)}
.br{position:absolute;pointer-events:none}
.br:before,.br:after,.br i:before,.br i:after{content:"";position:absolute;width:10px;height:10px;border:0 solid var(--amber)}
.br:before{left:0;top:0;border-width:3px 0 0 3px}.br:after{right:0;top:0;border-width:3px 3px 0 0}
.br i:before{left:0;bottom:0;border-width:0 0 3px 3px}.br i:after{right:0;bottom:0;border-width:0 3px 3px 0}
.rail{position:absolute;left:0;top:0;bottom:0;width:44px;background:var(--shell);border-right:1px solid var(--edge)}
.menu{height:40px;background:var(--amber);color:var(--ink);display:flex;align-items:center;justify-content:center}
.rail .band{height:6px;margin-bottom:8px}
.si{position:relative;height:40px;display:flex;align-items:center;justify-content:center;color:var(--dim)}
.si.cur{color:var(--amber)}.si.cur .br{left:6px;top:4px;width:32px;height:32px}
.top{position:absolute;left:44px;right:0;top:0;height:56px;background:var(--bar)}
.top .band{position:absolute;left:0;right:0;bottom:0;height:6px}
.search{position:absolute;left:20px;top:9px;width:260px;height:32px;background:var(--shell);border:1px solid var(--edge);display:flex;align-items:center;gap:8px;padding-left:10px;color:var(--dim)}
.search .ic{color:var(--amber)}
.items{position:absolute;left:296px;top:5px;display:flex;gap:4px}
.ti{position:relative;width:40px;height:40px;display:flex;align-items:center;justify-content:center;color:var(--dim)}
.ti.on{color:var(--amber)}.ti.on .br{left:2px;top:4px;right:2px;bottom:4px}
.win{position:absolute;right:12px;top:12px;display:flex}.win div{width:44px;height:32px;display:flex;align-items:center;justify-content:center;color:var(--dim)}
.btn{height:40px;padding:0 18px;display:flex;align-items:center;gap:8px;font-weight:700;background:var(--panel);border:1px solid var(--edge);color:var(--amber);position:relative}
.btn.play{background:var(--amber-strong);border-color:var(--amber-strong);color:var(--ink);font-size:16px;min-width:140px;justify-content:center}
.btn.hover{background:var(--raised)}.btn.hover .br{left:-4px;top:-4px;right:-4px;bottom:-4px}
h2{font-size:16px;font-weight:700;color:var(--amber);display:flex;align-items:center;gap:10px;margin-bottom:12px}
h2:before{content:"";width:8px;height:8px;background:var(--amber)}
.cap{color:var(--dim);font-size:12px}
.chip{display:inline-block;background:var(--cell);color:var(--text);font-size:12px;padding:3px 8px;margin:0 4px 4px 0}
</style></head><body>
"""


def shell(top_items):
    rail = ('<div class="rail"><div class="menu">%s</div><div class="band stripes"></div>'
            '<div class="si cur">%s<div class="br"><i></i></div></div><div class="si">%s</div></div>'
            % (icon("list", 18), icon("steering-wheel"), icon("chart-bar")))
    items = "".join('<div class="ti%s">%s%s</div>' % (" on" if on else "", icon(n, 18), '<div class="br"><i></i></div>' if on else "")
                    for n, on in top_items)
    top = ('<div class="top"><div class="band stripes"></div><div class="search">%s<span>Search</span></div>'
           '<div class="items">%s</div><div class="win"><div>%s</div><div>%s</div><div>%s</div></div></div>'
           % (icon("magnifying-glass"), items, icon("minus", 14), icon("square", 14), icon("x", 14)))
    return rail + top


def details():
    games = ["Burnout Paradise", "Crazy Taxi", "Dirt Rally 2.0", "Forza Horizon 4", "Gran Turismo 4", "Grid Legends",
             "Midnight Club 3", "Need a Lift", "Rockport Nights", "Ridge Racer Type 4", "Road Rash", "Test Drive Unlimited",
             "TrackMania Nations", "Wipeout HD", "Wreckfest"]
    rows = "".join('<div class="g%s">%s</div>' % (" sel" if g == "Rockport Nights" else "", g) for g in games)
    meta = [
        [("Completion", "Playing"), ("Time played", "41h 12m"), ("Last played", "Yesterday")],
        [("Critic score", '<b style="color:var(--lime)">82</b>'), ("User score", '<b style="color:var(--heat)">71</b>')],
        [("Developers", "Black Box Garage"), ("Publishers", "Rockport Media"), ("Release date", "15/11/2005")],
        [("Genres", '<span class="chip">Racing</span><span class="chip">Open world</span><span class="chip">Pursuit</span>'),
         ("Platform", '<span class="chip">PC (Windows)</span>')],
        [("Library", "Steam"), ("Install size", "3.2 GB")],
    ]
    groups = "".join('<div class="grp">%s</div>' % "".join(
        '<div class="f"><span class="cap">%s</span><span>%s</span></div>' % kv for kv in grp) for grp in meta)
    css = """<style>
.list{position:absolute;left:44px;top:56px;width:340px;bottom:0;padding:10px 4px;border-right:1px solid var(--rule)}
.g{height:30px;line-height:30px;padding-left:12px;margin-bottom:1px;color:var(--text);position:relative}
.g.sel{background:var(--select);color:var(--bright)}.g.sel:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--amber)}
.page{position:absolute;left:385px;right:0;top:56px;bottom:0;overflow:hidden}
.banner{position:absolute;left:0;right:0;top:0;height:340px;
background:radial-gradient(ellipse at 75% 35%,#7a6a3c 0%,#4a4128 28%,#2a2618 55%,transparent 80%),
radial-gradient(ellipse at 25% 60%,#3d4a3a 0%,#262a1f 40%,transparent 70%),linear-gradient(180deg,#3a3626,#1a170f)}
.banner:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(12,10,6,0) 10%,rgba(12,10,6,.75) 70%,var(--page) 100%)}
.wrap{position:absolute;left:32px;right:32px;top:100px}
h1{font-family:var(--title);font-weight:400;font-size:44px;color:var(--bright);line-height:1.1}
.tstripe{width:120px;height:6px;margin:10px 0 20px;background:repeating-linear-gradient(-45deg,var(--amber) 0 7px,var(--shell) 7px 14px)}
.acts{display:flex;gap:8px;margin-bottom:28px}
.cols{display:flex;gap:24px}.left{flex:1}
.shot{height:300px;background:linear-gradient(135deg,#3d3a2a,#16130c);position:relative}
.thumbs{display:flex;gap:8px;margin:8px 0 24px}.thumbs div{flex:1;height:58px;background:#2a2618}.thumbs div:first-child{outline:1px solid var(--amber);outline-offset:2px}
p{line-height:1.6;color:var(--text)}
.pane{position:relative;width:340px;background:var(--panel);border:1px solid var(--rule);padding:0 20px 12px}
.pane .br{left:-5px;top:-5px;right:-5px;bottom:-5px}
.phead{margin:0 -20px 8px;height:38px;position:relative}.phead span{position:absolute;left:0;top:0;bottom:0;background:var(--bar);padding:0 14px 0 20px;display:flex;align-items:center;color:var(--amber);font-weight:700;font-size:16px}
.grp{border-top:1px solid var(--rule);padding:6px 0}.grp:first-of-type{border:0}
.f{display:flex;padding:6px 0}.f .cap{width:112px;padding-top:2px;flex:none}
</style>"""
    shot_nav = '<div style="position:absolute;right:10px;bottom:10px;display:flex;gap:6px;color:var(--amber)">%s%s</div>' % (
        icon("caret-right", 18), "")
    body = ('<div class="list">%s</div><div class="page"><div class="banner"></div><div class="wrap">'
            '<h1>Rockport Nights</h1><div class="tstripe"></div>'
            '<div class="acts"><div class="btn play">Play</div><div class="btn hover">%s<span>More</span><div class="br"><i></i></div></div></div>'
            '<div class="cols"><div class="left"><h2>Screenshots</h2><div class="shot">%s</div><div class="thumbs"><div></div><div></div><div></div><div></div><div></div></div>'
            '<h2>Description</h2><p>The city of Rockport keeps a list of the fifteen most wanted street racers. Start at the bottom with a '
            'borrowed car and a clean rap sheet, win back your ride, and climb the Blacklist one rival at a time while the police '
            'raise their heat with every pursuit you escape.</p></div>'
            '<div class="pane"><div class="br"><i></i></div><div class="phead stripes"><span>Game details</span></div>%s</div>'
            '</div></div></div>'
            % (rows, icon("dots-three-outline", 16) if (CACHE / "dots-three-outline.svg").exists() else icon("dots-three", 16), shot_nav, groups))
    top = shell([("list-dashes", True), ("squares-four", False), ("rows", False), ("sliders-horizontal", False),
                 ("bookmark-simple", False), ("stack", False), ("arrows-down-up", False), ("funnel-simple", False)])
    return HEAD % dict(T, what="Details Preview", fonts=fonts()) + css + top + body + "</body></html>\n"


def settings():
    tabs = ["General", "Appearance", "Layouts", "Library", "Metadata", "Add-ons", "Performance", "Advanced"]
    tablist = "".join('<div class="tab%s">%s</div>' % (" sel" if t == "Appearance" else "", t) for t in tabs)
    css = """<style>
.dim{position:absolute;inset:0;background:rgba(5,3,1,.6)}
.dlg{position:absolute;left:260px;top:90px;width:1080px;height:720px;background:var(--page);border:1px solid var(--edge)}
.dlg>.br{left:-6px;top:-6px;right:-6px;bottom:-6px}
.dt{height:30px;position:relative}.dt span{position:absolute;left:0;top:0;bottom:0;background:var(--bar);padding:0 14px 0 12px;display:flex;align-items:center;color:var(--amber);font-weight:700}
.dt .x{position:absolute;right:0;top:0;bottom:0;width:44px;background:var(--bar);display:flex;align-items:center;justify-content:center;color:var(--dim)}
.tabs{position:absolute;left:0;top:30px;bottom:64px;width:220px;background:var(--panel);border-right:1px solid var(--rule);padding:12px 4px}
.tab{height:30px;line-height:30px;padding-left:14px;margin-bottom:2px;position:relative}
.tab.sel{background:var(--select);color:var(--bright)}.tab.sel:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--amber)}
.body{position:absolute;left:244px;right:24px;top:60px}
.gb{border:1px solid var(--rule);background:var(--panel);margin-bottom:20px}
.gbh{height:32px;position:relative}.gbh span{position:absolute;left:0;top:0;bottom:0;background:var(--bar);padding:0 10px;display:flex;align-items:center;color:var(--amber);font-weight:700}
.gbb{padding:12px 14px;display:grid;grid-template-columns:1fr 1fr;gap:14px 28px}
.chk{display:flex;align-items:center;gap:8px}
.box{width:18px;height:18px;border:2px solid var(--amber-dim);background:var(--bar);display:flex;align-items:center;justify-content:center}
.box.on{background:var(--amber);border-color:var(--amber);color:var(--ink)}
.rad .box.on{background:var(--bar);border-color:var(--amber)}.rad .box.on:after{content:"";width:8px;height:8px;background:var(--amber)}
.lbl{color:var(--dim);font-size:12px;margin-bottom:6px}
.inp{height:32px;background:var(--shell);border:1px solid var(--edge);display:flex;align-items:center;padding:0 8px;color:var(--text);position:relative}
.inp.focus{border-color:var(--amber)}.inp.focus .br{left:-4px;top:-4px;right:-4px;bottom:-4px}
.inp .ic{position:absolute;right:10px;color:var(--amber)}
.sl{height:20px;position:relative}.sl .r{position:absolute;left:0;right:0;top:8px;height:4px;background:var(--edge)}
.sl .f{position:absolute;left:0;top:8px;height:4px;background:var(--amber)}.sl .t{position:absolute;top:1px;width:6px;height:18px;background:var(--bright)}
.foot{position:absolute;left:0;right:0;bottom:0;height:64px;border-top:1px solid var(--rule);display:flex;justify-content:flex-end;align-items:center;gap:12px;padding:0 24px}
.foot .band{position:absolute;left:0;width:300px;top:0;bottom:0}
.btn.def{background:var(--amber-strong);border-color:var(--amber-strong);color:var(--ink);min-width:110px;justify-content:center}
.bar{height:6px;background:var(--edge);position:relative}.bar div{position:absolute;left:0;top:0;bottom:0;width:62%;background:var(--amber)}
</style>"""
    chk = lambda on, t: '<div class="chk"><div class="box%s">%s</div><span>%s</span></div>' % (" on" if on else "", icon("check", 12) if on else "", t)
    rad = lambda on, t: '<div class="chk rad"><div class="box%s"></div><span>%s</span></div>' % (" on" if on else "", t)
    body = ('<div class="dim"></div><div class="dlg"><div class="br"><i></i></div>'
            '<div class="dt stripes"><span>Settings</span><div class="x">%s</div></div>'
            '<div class="tabs">%s</div><div class="body">'
            '<div class="gb"><div class="gbh stripes"><span>Theme</span></div><div class="gbb">'
            '<div><div class="lbl">Desktop theme</div><div class="inp">Blacklist%s</div></div>'
            '<div><div class="lbl">Font</div><div class="inp focus">Eurostile<div class="br"><i></i></div></div></div>'
            '<div><div class="lbl">Cover art height</div><div class="sl"><div class="r"></div><div class="f" style="width:58%%"></div><div class="t" style="left:58%%"></div></div></div>'
            '<div><div class="lbl">Library update</div><div class="bar"><div></div></div></div>'
            '</div></div>'
            '<div class="gb"><div class="gbh stripes"><span>Layout</span></div><div class="gbb">'
            '%s%s%s%s%s%s'
            '</div></div>'
            '<div style="display:flex;gap:10px"><div class="btn">Reset layout</div><div class="btn hover">Open theme folder<div class="br"><i></i></div></div></div>'
            '</div>'
            '<div class="foot"><div class="band stripes"></div><div class="btn def">Save</div><div class="btn">Cancel</div></div></div>'
            % (icon("x", 12), tablist, icon("caret-down", 12),
               chk(True, "Show background art"), chk(True, "Show panel separators"), chk(False, "Show names under covers"),
               chk(True, "Darken uninstalled games"), rad(True, "Sidebar on the left"), rad(False, "Sidebar on the right")))
    top = shell([("list-dashes", False), ("squares-four", True), ("rows", False), ("sliders-horizontal", False),
                 ("bookmark-simple", False), ("stack", False), ("arrows-down-up", False), ("funnel-simple", False)])
    lib = '<div style="position:absolute;left:44px;right:0;top:56px;bottom:0;background:linear-gradient(180deg,#1d1a10,var(--page))"></div>'
    return HEAD % dict(T, what="Settings Preview", fonts=fonts()) + css + top + lib + body + "</body></html>\n"


if __name__ == "__main__":
    (ART / "preview-details.html").write_text(details(), encoding="utf-8")
    (ART / "preview-settings.html").write_text(settings(), encoding="utf-8")
    print("wrote preview-details.html and preview-settings.html")
