#!/usr/bin/env python3
"""Writes art/preview-details.html and art/preview-settings.html: 1280x720 HTML replicas of Blacklist in Playnite
(same sizes, shell and chrome as the XAML), rendered to screenshot-details.png / screenshot-settings.png by scripts/take-screenshots.ps1.

Colors are var(--mw-*) from src/tokens.css (the renderer injects it); only art placeholders (the banner and
screenshot gradients) use literal colors. Fonts are the theme's own stacks: the renderer draws Eurostile with Orbitron
and Old English Text MT with UnifrakturMaguntia (scripts/data/fonts.json), so nothing is embedded here. Icons are the
Phosphor bold geometries of src/Media.xaml (which art/icons.py generates), so this script needs no network.
Not shipped in the package.

    python3 art/previews.py          (from src/themes/Blacklist)
"""
import pathlib
import re

ART = pathlib.Path(__file__).resolve().parent
MEDIA = (ART.parent / "src" / "Media.xaml").read_text(encoding="utf-8")
GEO = {k: v for k, v in re.findall(r'<Geometry x:Key="(Icon[A-Za-z]+)">F1 ([^<]+)</Geometry>', MEDIA)}


def ic(key, size=16, cls=""):
    return ('<svg class="ic %s" width="%d" height="%d" viewBox="0 0 256 256" fill="currentColor"><path d="%s"/></svg>'
            % (cls, size, size, GEO["Icon" + key]))


HEAD = """<!doctype html>
<!-- Blacklist: HTML replica of Playnite (%(what)s), 1280x720. GENERATED by art/previews.py: edit the script, not this file.
     Colors are var(--mw-*) tokens from src/tokens.css. Motifs: black and amber hazard stripes on header bands, title
     bars and group headers; amber L brackets around the current item, hovered buttons, focus and the metadata pane;
     the blackletter game title; the 3px amber bar on the selected row; the solid amber Play / Save
     plate with dark ink. Unofficial fan replica: no EA assets, no game art, fictional game and studio. -->
<html><head><meta charset="utf-8"><title>Blacklist - %(what)s</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{width:1280px;height:720px;overflow:hidden;background:var(--mw-page);color:var(--mw-text);
font-family:"Eurostile", "Eurostile Extended", "Bahnschrift", "Segoe UI", sans-serif;font-size:14px;position:relative}
.ic{display:block;flex:none}
.stripes{background:repeating-linear-gradient(-45deg,var(--mw-stripe-bright) 0 7px,var(--mw-shell) 7px 14px)}
.br{position:absolute;pointer-events:none}
.br:before,.br:after,.br i:before,.br i:after{content:"";position:absolute;width:10px;height:10px;border:0 solid var(--mw-amber)}
.br:before{left:0;top:0;border-width:3px 0 0 3px}.br:after{right:0;top:0;border-width:3px 3px 0 0}
.br i:before{left:0;bottom:0;border-width:0 0 3px 3px}.br i:after{right:0;bottom:0;border-width:0 3px 3px 0}
.rail{position:absolute;left:0;top:0;bottom:0;width:44px;background:var(--mw-shell);border-right:1px solid var(--mw-edge)}
.menu{height:40px;background:var(--mw-amber);color:var(--mw-ink);display:flex;align-items:center;justify-content:center}
.rail .band{height:6px;margin-bottom:8px}
.si{position:relative;width:44px;height:40px;display:flex;align-items:center;justify-content:center;color:var(--mw-text-dim)}
.si.cur{color:var(--mw-amber)}.si.cur .br{left:6px;top:4px;width:32px;height:32px}
.top{position:absolute;left:44px;right:0;top:0;height:56px;background:var(--mw-bar)}
.top .band{position:absolute;left:0;right:0;bottom:0;height:6px}
.tbar{position:absolute;left:20px;top:9px;height:40px;display:flex;align-items:center}
.search{width:260px;height:32px;background:var(--mw-shell);border:1px solid var(--mw-edge);display:flex;align-items:center;gap:8px;padding-left:10px;color:var(--mw-text-dim)}
.search .ic{color:var(--mw-amber)}
.items{display:flex;margin-left:16px}
.ti{position:relative;width:40px;height:40px;margin:0 2px;display:flex;align-items:center;justify-content:center;color:var(--mw-text-dim)}
.ti.on{color:var(--mw-amber)}.ti.on .br{left:2px;top:4px;right:2px;bottom:4px}
.win{position:absolute;right:12px;top:12px;display:flex}.win div{width:44px;height:32px;display:flex;align-items:center;justify-content:center;color:var(--mw-text-dim)}
.btn{height:32px;padding:0 16px;display:flex;align-items:center;gap:8px;font-weight:700;background:var(--mw-panel);border:1px solid var(--mw-edge);color:var(--mw-amber);position:relative;white-space:nowrap}
.btn.hover{background:var(--mw-panel-raised)}.btn.hover .br{left:-4px;top:-4px;right:-4px;bottom:-4px}
.btn.plate{background:var(--mw-amber-strong);border-color:var(--mw-amber-strong);color:var(--mw-ink)}
h2{font-size:16px;font-weight:700;color:var(--mw-amber);display:flex;align-items:center;gap:10px;margin-bottom:12px;line-height:19px}
h2:before{content:"";width:8px;height:8px;background:var(--mw-amber)}
.cap{color:var(--mw-text-dim);font-size:12px}
.chip{display:inline-block;background:var(--mw-cell);color:var(--mw-text);font-size:12px;padding:3px 8px;margin:0 4px 4px 0}
</style></head><body>
"""


def shell(items, library_on):
    rail = ('<div class="rail" data-part="sidebar"><div class="menu" data-part="PART_ElemMainMenu">%s</div><div class="band stripes"></div>'
            '<div class="si%s">%s%s</div><div class="si">%s</div></div>'
            % (ic("MainMenu", 18), " cur" if library_on else "", ic("Library", 16), '<div class="br"><i></i></div>' if library_on else "",
               ic("Statistics", 16)))
    cells = "".join('<div class="ti%s">%s%s</div>' % (" on" if on else "", ic(n, 18), '<div class="br"><i></i></div>' if on else "")
                    for n, on in items)
    top = ('<div class="top" data-part="top-panel"><div class="band stripes"></div><div class="tbar">'
           '<div class="search" data-part="PART_TextMainSearch">%s<span>Search</span></div>'
           '<div class="items" data-part="PART_PanelMainItems">%s</div>'
           '<div class="ti" data-part="PART_ToggleFilter">%s</div>'
           '<div class="ti" data-part="PART_ToggleNotifications">%s</div></div>'
           '<div class="win"><div>%s</div><div>%s</div><div>%s</div></div></div>'
           % (ic("Search", 16), cells, ic("Filter", 18), ic("Notifications", 18),
              ic("WindowMinimize", 14), ic("WindowMaximize", 14), ic("WindowClose", 14)))
    return rail + top


def details():
    games = [("Burnout Paradise", 1), ("Crazy Taxi", 0), ("Dirt Rally 2.0", 1), ("Forza Horizon 4", 1), ("Gran Turismo 4", 0),
             ("Grid Legends", 1), ("Midnight Club 3", 1), ("Need a Lift", 0), ("Rockport Nights", 1), ("Ridge Racer Type 4", 0),
             ("Road Rash", 1), ("Test Drive Unlimited", 1), ("TrackMania Nations", 0), ("Wipeout HD", 1), ("Wreckfest", 1),
             ("Zoom Zoom Drift", 0)]
    rows = "".join('<div class="g%s%s">%s</div>' % (" sel" if n == "Rockport Nights" else "", "" if inst else " off", n) for n, inst in games)
    meta = [
        [("Time played", "41h 12m"), ("Last played", "Yesterday")],
        [("Critic score", '<b style="color:var(--mw-lime)">82</b>'), ("User score", '<b style="color:var(--mw-heat)">71</b>')],
        [("Developers", "Black Box Garage")],
        [("Genres", '<span class="chip">Racing</span><span class="chip">Pursuit</span>')],
    ]
    groups = "".join('<div class="grp">%s</div>' % "".join(
        '<div class="f"><span class="cap">%s</span><span>%s</span></div>' % kv for kv in grp) for grp in meta)
    css = """<style>
.bg{position:absolute;left:45px;right:0;top:56px;bottom:0;background:var(--mw-page)}
.list{position:absolute;left:45px;top:56px;width:280px;bottom:0;padding:10px 4px;border-right:1px solid var(--mw-rule);background:var(--mw-page)}
.g{height:30px;line-height:30px;padding-left:12px;margin-bottom:1px;color:var(--mw-text);position:relative;white-space:nowrap;overflow:hidden}
.g.off{color:var(--mw-text-dim)}
.g.sel{background:var(--mw-select);color:var(--mw-text-bright)}.g.sel:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--mw-amber)}
.note{position:absolute;left:12px;bottom:8px;font-size:11px;color:var(--mw-text-dim)}
.page{position:absolute;left:326px;right:0;top:56px;bottom:0;overflow:hidden}
.banner{position:absolute;left:0;right:0;top:0;height:340px;
background:radial-gradient(ellipse at 75% 30%,#7a6a3c 0%,#4a4128 28%,#2a2618 55%,transparent 80%),
radial-gradient(ellipse at 25% 60%,#3d4a3a 0%,#262a1f 40%,transparent 70%),linear-gradient(180deg,#3a3626,#1a170f)}
.banner:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,rgba(12,10,6,0) 10%,rgba(12,10,6,.75) 70%,var(--mw-page) 100%)}
.wrap{position:absolute;left:32px;right:32px;top:100px}
h1{font-family:"Old English Text MT", "UnifrakturMaguntia", "Bahnschrift", sans-serif;font-weight:400;font-size:33px;color:var(--mw-text);line-height:40px}
.acts{display:flex;gap:8px;margin:20px 0 24px}
.acts .btn{height:40px}.acts .play{min-width:140px;justify-content:center}.acts .sq{width:40px;padding:0;justify-content:center}
.cols{display:flex;gap:24px;align-items:flex-start}.left{flex:1;min-width:0}
.shot{height:168px;background:linear-gradient(135deg,#3d3a2a,#16130c);position:relative}
.shot .nav{position:absolute;right:10px;bottom:10px;color:var(--mw-amber)}
.thumbs{display:flex;gap:8px;margin:8px 0 24px}.thumbs div{flex:1;height:36px;background:#2a2618}.thumbs div:first-child{outline:1px solid var(--mw-amber);outline-offset:2px}
p{line-height:1.5;color:var(--mw-text)}
.pane{position:relative;width:340px;flex:none;background:var(--mw-panel);border:1px solid var(--mw-rule);padding:20px}
.pane>.br{left:-5px;top:-5px;right:-5px;bottom:-5px}
.phead{margin:-20px -20px 16px;position:relative}.phead span{display:inline-block;background:var(--mw-bar);padding:8px 14px 8px 20px;color:var(--mw-amber);font-weight:700;font-size:16px;line-height:19px;position:relative}
.phead{height:35px}.phead span{position:absolute;left:0;top:0;bottom:0}
.grp{border-top:1px solid var(--mw-rule);padding:12px 0}.phead+.grp{border:0;padding-top:0}.grp:last-child{padding-bottom:0}
.f{display:flex;padding:8px 0;line-height:19px}.f .cap{width:112px;flex:none;padding-top:3px}
</style>"""
    body = ('<div class="bg"></div><div class="list" data-part="game-list">%s<div class="note">Unofficial fan replica, no EA assets</div></div>'
            '<div class="page" data-part="game-page"><div class="banner"></div><div class="wrap">'
            '<h1>Rockport Nights</h1>'
            '<div class="acts"><div class="btn plate play">Play</div><div class="btn sq" title="More">%s</div><div class="btn sq" title="Edit">%s</div></div>'
            '<div class="cols"><div class="left"><h2>Screenshots</h2><div class="shot"><div class="nav">%s</div></div>'
            '<div class="thumbs"><div></div><div></div><div></div><div></div><div></div></div>'
            '<h2>Description</h2><p>Rockport keeps a list of its fifteen most wanted street racers. Start with a borrowed car and a '
            'clean rap sheet, win back your ride and climb the Blacklist one rival at a time.</p></div>'
            '<div class="pane" data-part="metadata"><div class="br"><i></i></div><div class="phead stripes"><span>Game details</span></div>%s</div>'
            '</div></div></div>'
            % (rows, ic("Options", 18), ic("Edit", 18), ic("Submenu", 18), groups))
    top = shell([("DetailsView", True), ("GridView", False), ("ListView", False), ("ViewSettings", False),
                 ("FilterPresets", False), ("Group", False), ("Sort", False)], True)
    return HEAD % {"what": "Details Preview"} + css + top + body + "</body></html>\n"


def settings():
    node = lambda t, lvl=0, sel=False, ex=None: (
        '<div class="node%s%s"><span class="tw">%s</span>%s</div>'
        % (" l2" if lvl else "", " sel" if sel else "", ic("DropDown" if ex else "Submenu", 10) if ex is not None else "", t))
    tree = "".join([
        node("General"), node("Appearance", ex=True), node("General", 1, True), node("Advanced", 1), node("Details View", 1),
        node("Grid View", 1), node("List View", 1), node("Layout", 1), node("Top panel", 1),
        node("Search"), node("Updating"), node("Metadata"), node("Sorting"), node("Scripts"), node("Auto Close Clients"),
        node("Import Exclusion List"), node("Backup"), node("For developers"), node("Input"), node("Advanced", ex=True),
        node("Performance", 1)])
    css = """<style>
.dim{position:absolute;inset:0;background:radial-gradient(ellipse at 50% 40%,#1f180c 0%,var(--mw-page) 70%)}
.dlg{position:absolute;left:180px;top:20px;width:920px;height:680px;background:var(--mw-page);border:1px solid var(--mw-edge);display:flex;flex-direction:column}
.dt{height:30px;flex:none;position:relative}.dt span{position:absolute;left:0;top:0;bottom:0;background:var(--mw-bar);padding:0 14px 0 12px;display:flex;align-items:center;color:var(--mw-amber);font-weight:700}
.dt .x{left:auto;right:0;width:44px;padding:0;justify-content:center;color:var(--mw-text-dim)}
.body{flex:1;min-height:0;display:flex}
.tabs{width:236px;flex:none;border-right:1px solid var(--mw-rule);padding:6px 4px;overflow:hidden}
.node{height:25px;display:flex;align-items:center;padding-left:6px;color:var(--mw-text);white-space:nowrap}
.node.l2{padding-left:22px}.node.sel{background:var(--mw-select);color:var(--mw-text-bright)}
.node .tw{width:14px;display:flex;color:var(--mw-text-dim)}
.content{flex:1;min-width:0;padding:14px;overflow:hidden}
.gb{border:1px solid var(--mw-rule);background:var(--mw-panel);margin-bottom:12px}
.gbh{height:31px;position:relative}.gbh span{position:absolute;left:0;top:0;bottom:0;background:var(--mw-bar);padding:0 10px;display:flex;align-items:center;color:var(--mw-amber);font-weight:700}
.gbb{padding:12px}
.row{display:flex;align-items:center;gap:8px;min-height:26px}.row+.row{margin-top:8px}
.box{width:18px;height:18px;flex:none;border:2px solid var(--mw-amber-dim);background:var(--mw-bar);display:flex;align-items:center;justify-content:center}
.box.on{background:var(--mw-amber);border-color:var(--mw-amber);color:var(--mw-ink)}
.rad.sel:after{content:"";width:8px;height:8px;background:var(--mw-amber)}
.lbl{color:var(--mw-text-dim);font-size:12px}
.inp{height:32px;background:var(--mw-shell);border:1px solid var(--mw-edge);display:flex;align-items:center;justify-content:space-between;padding:0 8px;color:var(--mw-text);position:relative}
.inp.focus{border-color:var(--mw-amber)}.inp.focus .br{left:-4px;top:-4px;right:-4px;bottom:-4px}
.inp .ic{color:var(--mw-amber)}
.inp.cb{padding:0 30px 0 8px}.inp.cb .ic{position:absolute;right:10px;top:10px}
.sl{height:20px;position:relative;width:260px}.sl .r{position:absolute;left:0;right:0;top:8px;height:4px;background:var(--mw-edge)}
.sl .fl{position:absolute;left:0;top:8px;height:4px;background:var(--mw-amber)}.sl .t{position:absolute;top:1px;width:6px;height:18px;background:var(--mw-text-bright)}
.foot{height:56px;flex:none;border-top:1px solid var(--mw-rule);display:flex;justify-content:space-between;align-items:center;padding:0 14px}
.foot .note{font-size:12px;color:var(--mw-text-dim)}.foot .bs{display:flex;gap:8px}.foot .btn{min-width:96px;justify-content:center}
</style>"""
    chk = lambda on, t: '<div class="row"><div class="box%s">%s</div><span>%s</span></div>' % (" on" if on else "", ic("Check", 12) if on else "", t)
    rad = lambda on, t: '<div class="box rad%s"></div><span>%s</span>' % (" sel" if on else "", t)
    body = ('<div class="dim"></div><div class="dlg" data-part="settings-window">'
            '<div class="dt stripes"><span>Settings</span><span class="x">%s</span></div><div class="body">'
            '<div class="tabs" data-part="settings-nav">%s</div><div class="content" data-part="settings-content">'
            '<div class="gb"><div class="gbh stripes"><span>Details View</span></div><div class="gbb">%s%s'
            '<div class="row lbl" style="margin-top:12px">Details view game list position</div>'
            '<div class="row">%s<span style="width:12px"></span>%s</div></div></div>'
            '<div class="gb"><div class="gbh stripes"><span>Grid View</span></div><div class="gbb">%s'
            '<div class="row" style="margin-top:12px"><span class="lbl" style="width:160px">Item spacing</span>'
            '<div class="sl"><div class="r"></div><div class="fl" style="width:60%%"></div><div class="t" style="left:calc(60%% - 3px)"></div></div><span class="lbl">12</span></div>'
            '<div class="row"><span class="lbl" style="width:160px">Grid item border width</span><div class="inp" style="width:72px">4</div></div></div></div>'
            '<div class="gb"><div class="gbh stripes"><span>Theme</span></div><div class="gbb">'
            '<div class="row"><span class="lbl" style="width:160px">Desktop theme</span><div class="inp cb focus" style="width:220px">Blacklist%s<div class="br"><i></i></div></div><div class="inp cb" style="width:auto;margin-left:12px">Minimize%s</div></div>'
            '<div class="row"><span class="lbl" style="width:160px">Font Size</span><div class="inp" style="width:72px">14</div><span class="lbl">px</span></div></div></div>'
            '</div></div>'
            '<div class="foot" data-part="settings-buttons"><span class="note">* Requires restart to apply</span>'
            '<div class="bs"><div class="btn plate">Save</div><div class="btn hover">Cancel<div class="br"><i></i></div></div></div></div></div>'
            % (ic("WindowClose", 12), tree, chk(True, "Show game icons on Details view list"), chk(False, "Show item count on group descriptions"),
               rad(True, "Left"), rad(False, "Right"), chk(True, "Show game names on Grid view"), ic("DropDown", 12), ic("DropDown", 12)))
    return HEAD % {"what": "Settings Preview"} + css + body + "</body></html>\n"


if __name__ == "__main__":
    (ART / "preview-details.html").write_text(details(), encoding="utf-8")
    (ART / "preview-settings.html").write_text(settings(), encoding="utf-8")
    print("wrote preview-details.html and preview-settings.html")
