// Generates the per-add-on README.md files and keeps the Details / Download links in the root README current.
//   node scripts/generate-readmes.mjs            write everything
//   node scripts/generate-readmes.mjs --check    exit 1 if a generated file is out of date (CI, npm run check:readmes)
//
// Sources: src/extensions.json (key, name, kind, dir), <dir>/info/danitesler_<key>.yaml (description, screenshots,
// tags, links), <dir>/info/theme.yaml or extension.yaml (version, API), info/NOTICE-*.txt and LICENSE-*.txt, and the
// git tags `<key>-v<version>` (an add-on counts as released when such a tag exists).
//
// Rules: a README is only overwritten when it is missing or starts with the generated marker, so a hand-written one
// (RandomTheme) is kept. The root README keeps its hand-written row text; only the final links line of each add-on row
// is rewritten.
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const REPO = 'https://github.com/danitesler/playnite-extensions';
const RAW = 'https://raw.githubusercontent.com/danitesler/playnite-extensions/main/';
const MARKER = '<!-- Generated by scripts/generate-readmes.mjs from info/*.yaml and git tags. Edit those, then re-run it; do not edit this file by hand. -->';

const read = (p) => fs.readFileSync(path.join(root, p), 'utf8').replace(/\r\n/g, '\n');
const exists = (p) => fs.existsSync(path.join(root, p));

// ---- minimal YAML reader for the flat shapes these manifests use --------------------------------------------------
function parseYaml(text) {
  const out = {};
  const lines = text.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const m = /^([A-Za-z][\w ]*):\s*(.*)$/.exec(lines[i]);
    if (!m) continue;
    const [, key, rest] = m;
    if (rest === '|') {
      const body = [];
      for (i++; i < lines.length && (lines[i] === '' || /^\s+/.test(lines[i])); i++) body.push(lines[i].replace(/^ {2}/, ''));
      i--;
      out[key] = body.join('\n').trim();
    } else if (rest === '') {
      const items = [];
      for (i++; i < lines.length && /^\s+/.test(lines[i]); i++) items.push(lines[i]);
      i--;
      out[key] = items;
    } else if (rest.startsWith('[')) {
      out[key] = rest.replace(/^\[|\]$/g, '').split(',').map((s) => s.trim()).filter(Boolean);
    } else {
      out[key] = rest.replace(/^["']|["']$/g, '');
    }
  }
  return out;
}

function linksOf(items) { // "  Label: https://..." lines
  return (items || []).map((l) => /^\s+(.+?):\s+(https?:\/\/\S+)\s*$/.exec(l)).filter(Boolean).map((m) => ({ label: m[1], url: m[2] }));
}
function screenshotsOf(items) { // "  - Thumbnail: url / Image: url"
  const urls = [];
  for (const l of items || []) {
    const m = /^\s+(?:-\s+)?Image:\s+(\S+)\s*$/.exec(l);
    if (m) urls.push(m[1]);
  }
  return urls;
}

// ---- releases ------------------------------------------------------------------------------------------------
let tags = [];
try { tags = execSync('git tag --list', { cwd: root, encoding: 'utf8' }).split('\n').filter(Boolean); } catch { /* no git */ }
const haveTags = tags.length > 0;
const semver = (v) => v.split('.').map(Number);
const cmp = (a, b) => { const x = semver(a), y = semver(b); for (let i = 0; i < 3; i++) if (x[i] !== y[i]) return x[i] - y[i]; return 0; };
// Safety net: a release the root README already links but whose tag is not in this clone (shallow clone, tags not
// fetched) is kept instead of being silently turned into "not released yet".
const linkedInReadme = new Map();
for (const m of read('README.md').matchAll(/releases\/tag\/([a-z0-9]+)-v(\d+\.\d+\.\d+)/g)) {
  const prev = linkedInReadme.get(m[1]);
  if (!prev || cmp(m[2], prev) > 0) linkedInReadme.set(m[1], m[2]);
}
const warned = new Set();
function latestRelease(key) {
  const vs = tags.map((t) => new RegExp(`^${key}-v(\\d+\\.\\d+\\.\\d+)$`).exec(t)).filter(Boolean).map((m) => m[1]).sort(cmp);
  let version = vs.length ? vs[vs.length - 1] : null;
  const linked = linkedInReadme.get(key);
  if (linked && (!version || cmp(linked, version) > 0)) {
    if (!warned.has(key)) { warned.add(key); console.log(`warning: README links ${key}-v${linked} but that tag is not in this clone (git fetch --tags); keeping the link`); }
    version = linked;
  }
  return version ? { version, tag: `${key}-v${version}`, url: `${REPO}/releases/tag/${key}-v${version}` } : null;
}

// ---- per add-on README -----------------------------------------------------------------------------------------
const catalog = JSON.parse(read('src/extensions.json'));
const addons = (Array.isArray(catalog) ? catalog : Object.values(catalog).find(Array.isArray))
  .map((e) => ({ ...e, isTheme: e.kind === 'theme' }));

function installSteps(a, ext) {
  const file = a.isTheme ? '`.pthm`' : '`.pext`';
  const steps = [
    `1. **Inside Playnite:** open **Add-ons** from the main menu, browse or search for **${a.name}**, and install it from there.`,
    `2. **Or from GitHub:** download the ${file} file from the release page (see Download above) and open it in **Windows** (double-click it or drag it onto Playnite).`,
    '3. Click **Install** when Playnite prompts you, then restart Playnite.',
  ];
  if (a.isTheme) steps.push('4. Pick the theme in **Settings → Appearance → General → Theme** (Desktop mode), then restart Playnite if it asks.');
  return steps.join('\n');
}

function buildReadme(a) {
  const info = `${a.dir}/info`;
  const listing = parseYaml(read(`${info}/danitesler_${a.key}.yaml`));
  const manifest = parseYaml(read(`${info}/${a.isTheme ? 'theme' : 'extension'}.yaml`));
  const rel = latestRelease(a.key);
  const kind = a.isTheme ? 'Theme' : 'Plugin';
  const desc = (listing.Description || listing.ShortDescription || '').trim();
  const shots = screenshotsOf(listing.Screenshots).map((u) => u.replace(RAW + a.dir + '/', ''));
  const links = linksOf(listing.Links).filter((l) => !/homepage|report issue/i.test(l.label));
  const notices = fs.readdirSync(path.join(root, info)).filter((f) => /^(NOTICE|LICENSE).*\.txt$/.test(f)).sort();

  const out = [MARKER, '', `# ${a.name}`, ''];
  out.push(`<img src="info/icon.png" alt="${a.name}" width="64" height="64" />`, '');
  out.push(`**${listing.ShortDescription || ''}**`, '');
  out.push(rel ? `**[Download ${a.name} ${rel.version}](${rel.url})**` : '_Not released yet._', '');
  if (shots.length) {
    out.push('## Screenshots', '');
    out.push(shots.map((s, i) => `<a href="${s}"><img src="${s}" alt="${a.name} screenshot ${i + 1}" width="49%" /></a>`).join(' '), '');
  }
  out.push('## About', '', desc, '');
  out.push('## Install', '', installSteps(a, manifest), '');
  out.push('## Details', '');
  out.push(`- **Type:** ${kind}${a.isTheme ? ` (${manifest.Mode || 'Desktop'} mode)` : ''}`);
  out.push(`- **Latest release:** ${rel ? `[${rel.version}](${rel.url})` : 'not released yet'}`);
  if (manifest.ThemeApiVersion) out.push(`- **Playnite theme API:** ${manifest.ThemeApiVersion}`);
  else if (manifest.Type) out.push(`- **Extension type:** ${manifest.Type}`);
  if (listing.Tags?.length) out.push(`- **Tags:** ${listing.Tags.join(', ')}`);
  for (const l of links) out.push(`- **${l.label}:** ${l.url}`);
  out.push(`- **Source:** [${a.dir}](${REPO}/tree/main/${a.dir})`);
  out.push(`- **Issues and suggestions:** [GitHub issues](${REPO}/issues)`);
  if (notices.length) {
    out.push('', '## Notices and licenses', '');
    for (const n of notices) out.push(`- [${n}](info/${n})`);
  }
  out.push('', '---', '', `[← All add-ons](${'../'.repeat(a.dir.split('/').length)}README.md)`, '');
  return out.join('\n');
}

// ---- root README rows --------------------------------------------------------------------------------------------
function linksLine(a) {
  const rel = latestRelease(a.key);
  return `[Details](${a.dir}/README.md) · ${rel ? `[Download ${rel.version}](${rel.url})` : '_not released yet_'}`;
}

function updateRootReadme(text) {
  const lines = text.split('\n');
  const used = new Set();
  const out = lines.map((line) => {
    if (!line.startsWith('| ')) return line;
    const a = addons.find((x) => line.includes(`${x.dir}/info/icon.png`) || line.includes(`${x.dir}/art/screenshot-details.png`));
    if (!a) return line;
    used.add(a.key);
    // first cell = icon or preview, second = name, text and links
    const cells = line.replace(/^\|\s*/, '').replace(/\s*\|\s*$/, '').split(/ \| /);
    const first = cells.shift();
    const cell = cells.join(' | ');
    const parts = cell.split('<br>');
    const name = `**${a.name}**`;
    const desc = parts.length > 1 ? parts[1] : '';
    return `| ${first} | ${name}<br>${desc}<br>${linksLine(a)} |`;
  });
  const missing = addons.filter((a) => !used.has(a.key)).map((a) => a.key);
  return { text: out.join('\n'), missing };
}

// ---- run ----------------------------------------------------------------------------------------------------------
let stale = 0;
const note = (m) => console.log(m);

for (const a of addons) {
  const p = `${a.dir}/README.md`;
  const next = buildReadme(a);
  if (exists(p)) {
    const cur = read(p);
    if (!cur.startsWith(MARKER.slice(0, 40))) { note(`kept hand-written ${p}`); continue; }
    if (cur === next) continue;
  }
  stale++;
  if (check) note(`out of date: ${p}`);
  else { fs.writeFileSync(path.join(root, p), next, 'utf8'); note(`wrote ${p}`); }
}

const rootCur = read('README.md');
const { text: rootNext, missing } = updateRootReadme(rootCur);
if (missing.length) note(`warning: no root README row for: ${missing.join(', ')}`);
if (rootNext !== rootCur) {
  stale++;
  if (check) note('out of date: README.md');
  else { fs.writeFileSync(path.join(root, 'README.md'), rootNext, 'utf8'); note('updated README.md'); }
}
if (!haveTags) note('warning: no git tags found; Download links assume nothing is released (fetch tags before --check)');
if (check && stale) { console.error(`${stale} generated file(s) out of date: run node scripts/generate-readmes.mjs`); process.exit(1); }
if (check) note('readmes up to date');
